name: "Build browser component"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
        default: 1.0.1
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Check file on S3
        env:
          EXISTED: 254
        run: echo "EXISTED=$(aws s3api head-object --bucket 'herond-ext-updater-prod' --key 'release/dlibgjfecknlggedcgaabhmefdkfdkgp/extension_1_0_1.crx' >/dev/null 2>1; echo $?)" >> $GITHUB_ENV
        shell: bash
      - name: Extension exists - STOP
        if: ${{ env.EXISTED != 254 }}
        run: exit 1
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Download browser tool
        run: curl -L -o browser.zip ${{ vars.BROWSER_ZIP_FILE_URL }}
        shell: bash
      - name: Unzip tool
        run: 7z x browser.zip -obrowser
      - name: Prepare publisher key
        env: 
          PUBLISHER_KEY: ${{ secrets.HEROND_EXTENSION_PUBLISHER_KEY }}
        run: echo "$PUBLISHER_KEY" | base64 --decode > publisher.pem
        shell: bash
      - name: Prepare extension key
        env: 
          EXTENSION_KEY: ${{ secrets.HEROND_FILTER_LIST_KEY }}
        run: echo "$EXTENSION_KEY" | base64 --decode > herondlist.pem
        shell: bash
      - name: Build Herond List
        run: npm run gen_herond_list -- --executable_herond="${{ github.workspace }}\browser\herond.exe" --private_key="${{ github.workspace }}\herondlist.pem" --publisher_key="${{ github.workspace }}\publisher.pem"
      - name: Check output
        run: cd build && dir
