name: "Build browser component"
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Version
        required: true
        default: 1.0.1
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Check version
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HEROND_EXTENSION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEROND_EXTENSION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'
        run: npm run actions:check_version -- --version="${{ inputs.version }}" --type=1
      - name: Download browser tool
        run: curl -L -o browser.zip ${{ vars.BROWSER_ZIP_FILE_URL }}
        shell: bash
      - name: Unzip tool
        run: 7z x browser.zip -obrowser
      - name: Prepare publisher key
        env:
          PUBLISHER_KEY: ${{ secrets.HEROND_EXTENSION_PUBLISHER_KEY }}
        run: echo "$PUBLISHER_KEY" | base64 --decode > publisher.pem
        shell: bash
      - name: Prepare extension key
        env:
          EXTENSION_KEY: ${{ secrets.HEROND_FILTER_LIST_KEY }}
        run: echo "$EXTENSION_KEY" | base64 --decode > herondlist.pem
        shell: bash
      - name: Build Herond List
        run: npm run build -- --executable_herond="${{ github.workspace }}\browser\herond.exe" --private_key="${{ github.workspace }}\herondlist.pem" --publisher_key="${{ github.workspace }}\publisher.pem" --version="${{ inputs.version }}"
      - name: Upload extension to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HEROND_EXTENSION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEROND_EXTENSION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'
        run: npm run actions:upload -- --version="${{ inputs.version }}"
      - name: Update DB
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HEROND_EXTENSION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEROND_EXTENSION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'
        run: npm run actions:update_db -- --version="${{ inputs.version }}"