name: "Build browser component"
on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        type: boolean
        default: true
  schedule:
    - cron: '0 0 * * 5' # Every Friday at 00:00 UTC
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Set build version
        id: build_ver
        run: echo "version=${{ vars.HEROND_LIST_VERSION_MAJOR }}.${{ vars.HEROND_LIST_VERSION_MINOR }}.$((${{ vars.HEROND_LIST_VERSION_PATCH }}+1))" >> $GITHUB_OUTPUT
        shell: bash
      - name: Check version
        if: ${{ inputs.release == true }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HEROND_EXTENSION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEROND_EXTENSION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'
        run: npm run actions:check_version -- --version="${{ steps.build_ver.outputs.version }}"
      - name: Download browser tool
        run: curl -L -o browser.zip ${{ vars.BROWSER_ZIP_FILE_URL }}
        shell: bash
      - name: Unzip tool
        run: 7z x browser.zip -obrowser
      - name: check output
        run: |
          ls
          cd "${{ github.workspace }}\browser"
          ls
        shell: bash
      - name: Prepare publisher key
        env:
          PUBLISHER_KEY: ${{ secrets.HEROND_EXTENSION_PUBLISHER_KEY }}
        run: echo "$PUBLISHER_KEY" | base64 --decode > publisher.pem
        shell: bash
      - name: Prepare extension key
        env:
          EXTENSION_KEY: ${{ secrets.HEROND_FILTER_LIST_KEY }}
        run: echo "$EXTENSION_KEY" | base64 --decode > herondlist.pem
        shell: bash
      - name: Build Herond List
        run: npm run build -- --executable_herond="${{ github.workspace }}\browser\herond.exe" --private_key="${{ github.workspace }}\herondlist.pem" --publisher_key="${{ github.workspace }}\publisher.pem" --version="${{ steps.build_ver.outputs.version }}"
      - name: Upload extension to S3
        if: ${{ inputs.release == true }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HEROND_EXTENSION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEROND_EXTENSION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'
        run: npm run actions:upload -- --version="${{ steps.build_ver.outputs.version }}"
      - name: Update DB
        if: ${{ inputs.release == true }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.HEROND_EXTENSION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.HEROND_EXTENSION_AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: 'ap-southeast-1'
        run: npm run actions:update_db -- --version="${{ steps.build_ver.outputs.version }}"
      - name: Increase version
        if: ${{ inputs.release == true }}
        env:
          GH_TOKEN: ${{ secrets.HEROND_DEVOPS_PAT }}
        run: gh variable set HEROND_LIST_VERSION_PATCH --body=$((${{ vars.HEROND_LIST_VERSION_PATCH }}+1))
